<script lang="ts">
	import { panel, closePanel } from '$lib/stores/ui.svelte.js';
	import { setFocus } from '$lib/stores/scene.svelte.js';

	function handleClose() {
		setFocus(null);
		closePanel();
	}

	function handleKeydown(e: KeyboardEvent) {
		if (e.key === 'Escape') handleClose();
	}
</script>

<svelte:window on:keydown={handleKeydown} />

<div
	class="panel"
	class:open={panel.open}
	role="dialog"
	aria-modal="true"
	aria-label={panel.content?.title ?? 'Detail panel'}
	aria-hidden={!panel.open}
>
	<button class="panel-close" onclick={handleClose} aria-label="Close panel">✕</button>

	{#if panel.content}
		<h2 class="panel-title">{panel.content.title}</h2>
		<!-- eslint-disable-next-line svelte/no-at-html-tags -->
		<div class="panel-body">{@html panel.content.html}</div>
	{/if}
</div>

<!-- Backdrop -->
{#if panel.open}
	<button class="panel-backdrop" onclick={handleClose} aria-label="Close panel" tabindex="-1"></button>
{/if}

<style>
	.panel {
		position: fixed;
		top: 50%;
		right: -420px;
		transform: translateY(-50%);
		width: min(400px, 90vw);
		max-height: 80vh;
		overflow-y: auto;
		background: rgba(10 12 28 / 0.92);
		backdrop-filter: blur(16px);
		border: 1px solid rgba(100 130 255 / 0.2);
		border-radius: 16px;
		padding: 28px 24px 24px;
		z-index: 20;
		transition: right 0.35s cubic-bezier(0.34, 1.56, 0.64, 1);
		color: #e8eeff;
		box-shadow: 0 24px 80px rgba(0 0 0 / 0.6);
	}

	.panel.open {
		right: 24px;
	}

	.panel-close {
		position: absolute;
		top: 12px;
		right: 16px;
		background: none;
		border: none;
		color: rgba(255 255 255 / 0.5);
		font-size: 18px;
		cursor: pointer;
		padding: 4px 8px;
		border-radius: 6px;
		transition: color 0.15s, background 0.15s;
	}

	.panel-close:hover {
		color: #fff;
		background: rgba(255 255 255 / 0.1);
	}

	.panel-title {
		font-size: 20px;
		font-weight: 700;
		margin: 0 0 20px;
		color: #c8d8ff;
	}

	.panel-body {
		font-size: 14px;
		line-height: 1.7;
	}

	/* Linktree-style dynamic content styles (generated by ui.svelte.ts) */
	:global(.linktree-panel) {
		display: flex;
		flex-direction: column;
		gap: 12px;
	}

	:global(.linktree-subtitle) {
		margin: 0;
		font-size: 13px;
		line-height: 1.5;
		color: rgba(255 255 255 / 0.58);
	}

	:global(.linktree-list) {
		display: flex;
		flex-direction: column;
		gap: 10px;
	}

	:global(.linktree-item) {
		display: flex;
		flex-direction: column;
		gap: 4px;
		padding: 12px 14px;
		border-radius: 12px;
		text-decoration: none;
		background: rgba(255 255 255 / 0.04);
		border: 1px solid rgba(255 255 255 / 0.1);
		transition: transform 0.16s ease, border-color 0.16s ease, background 0.16s ease;
	}

	:global(.linktree-item:hover) {
		transform: translateX(4px);
		border-color: rgba(124 163 255 / 0.65);
		background: rgba(95 125 225 / 0.16);
	}

	:global(.linktree-head) {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 10px;
	}

	:global(.linktree-label) {
		font-size: 14px;
		font-weight: 650;
		color: #d8e4ff;
	}

	:global(.linktree-badge) {
		font-size: 11px;
		font-weight: 600;
		padding: 3px 8px;
		border-radius: 20px;
		background: rgba(106 136 255 / 0.22);
		color: #c9d7ff;
		border: 1px solid rgba(106 136 255 / 0.42);
	}

	:global(.linktree-desc) {
		font-size: 12px;
		line-height: 1.45;
		color: rgba(255 255 255 / 0.62);
	}

	.panel-backdrop {
		position: fixed;
		inset: 0;
		z-index: 19;
		background: transparent;
		border: none;
		cursor: default;
	}

	@media (max-width: 600px) {
		.panel {
			top: auto;
			bottom: -100vh;
			right: 0;
			left: 0;
			width: 100%;
			max-height: 65vh;
			border-radius: 20px 20px 0 0;
			transform: none;
			transition: bottom 0.35s cubic-bezier(0.34, 1.56, 0.64, 1);
		}

		.panel.open {
			right: 0;
			bottom: 0;
		}
	}
</style>
